basePath: /v2
definitions:
  responses.CreateResponse:
    properties:
      assetId:
        example: a
        type: string
      hash:
        example: 96e75810b7fe519dd92f6a3f72170b00c0a8a9553f9c765a3cc681eaf7eeab38
        type: string
      merkleRoot:
        example:
        - Vu14mZ91jlhkqHhjFwmgjXgxyhLjLADVQlqMSQA3Q3o=
        items:
          type: byte
        type: array
      timestamp:
        example: 1536920750859
        type: integer
      txNumber:
        example: 0
        type: integer
    type: object
host: history.bankex.team
info:
  contact:
    email: nk@bankexfoundation.org
    name: API Support
  description: This is POA History swagger documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger History API
  version: "1.0"
paths:
  /a/new/{assetId}/{hash}:
    post:
      consumes:
      - text/plain
      description: add hash by assetId
      parameters:
      - description: assetId
        in: path
        name: assetId
        required: true
        type: string
      - description: Hash of file
        in: path
        name: hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.CreateResponse'
            type: array
      summary: Add a new asset to assetId
swagger: "2.0"
