version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: erage/server
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
    - "8080:8080"
    - "27017:27017"
    networks:
    - webnet

networks:
  webnet:


