version 3
services
  web
    # replace usernamerepotag with your name and image details
    image erageserver
    deploy
      replicas 1
      resources
        limits
          cpus “0.9”
          memory 550M
      restart_policy
        condition on-failure
    build 
      args
        PVT_KEY 'fb4346d4d7518c159c809f62fb6ab0152f7ca878bf7fddc056d6b02a3c917653'
        CONTRACT_ADDRESS '0x0293a80682dc2a192c683baf434dd67343cebf70'
        LOGIN_DB 'bankex2'
        PASSWORD_DB 'ObshiDostup1'
        IP '18.209.40.150'
        LOGIN 'bankex'
        PASSWORD 'ObshiDostup1'
    ports
    - 80808080
    - 2701727017
    networks
    - webnet
  
networks
  webnet